config/routes.rb
Rails.application.routes.draw do
	devise_for :users
	root 'posts#index'
	resources :users do
		get '/posts/:post_id/like' => 'likes#like', as: 'like'
		delete '/posts/:post_id/dislike' => 'likes#dislike', as: 'dislike'
		post 'following' => 'users#following', as: 'following'
		get 'followers' => 'users#followers', as: 'followers'
		resources :posts do
			resources :comments
			resources :likes
		end
	end
	resources :users
	resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many_attached :images
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :likes
	has_many :users, through: :likes
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	validates :name, presence: true, length: { maximum: 50 }
	has_one_attached :avatar
	has_many :posts, dependent: :destroy
	has_many :comments, dependent: :destroy
	has_many :likes
	has_many :comments, through: :likes
	has_many :followers, through: :relationships
	has_many :followed, through: :relationships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	private

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
		
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def new
		@comment = Comment.new
		@user = User.find(params[:user_id])
		@post = Post.find(params[:post_id])
	end

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id



		if @comment.save
			flash[:success] = "You commented the hell out of that post!"
			redirect_back(fallback_location: root_path)
		else
			flash[:alert] = "Check the comment form, something went horribly wrong."
			render root_path
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:content, :post_id, :user_id)
	end

	def set_post
		@post = Post.find(params[:post_id])
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def like
		@post = Post.find(params[:post_id])
		@user = current_user.id
		@like = @post.likes.create(user: current_user)
		redirect_back(fallback_location: root_path)
	end

	def dislike
		@post = Post.find(params[:post_id])
		@user = current_user
		@likes = @post.likes.all
		@like = @likes.where(user_id: @user.id)
		@like.delete(@like)
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
		@user = current_user

	end

	def new
		@post = Post.new
		@user = User.find(params[:user_id])
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = current_user.posts.build(post_params)
		@user = User.find(params[:user_id])

		if @post.save
			redirect_to user_posts_path
		else
			render 'new'
		end
	end

	def post_params
      params.require(:post).permit(:description, :user_id, :comment_id, images: [])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
    
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def following
  #   Relationships.new(:followed_id, @user.id)
  #   user_id: current_user.id
    
  # end

  # def followers

  # end


  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_new.html.erb
<%= form_with model: @comment, url: user_post_comments_path(current_user.id, post.id), scope: :comment, local: true do |form| %>
  <div class="field">
    <%= form.text_field :content, placeholder: 'Add a comment...' %>

  <div class="actions">
    <%= form.submit 'Add comment' %>
  </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar fixed navbar-dark bg-dark navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      &#x2630;
    </button>
    <div class="navbar-nav ml-auto">
      <div class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <div class="nav-item">
          <span class="navbar-text">
            Hello, &nbsp;
            <span>
            </div>
            <div class="dropdown show">
              <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </div>
              <div>
                <% else %>
                <div class="nav-item">
                 <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
               </div>
               <div class="nav-item">
                 <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
               </div>
               <% end %>
             </div>
           </div>
         </div>
       </div>
     </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="d-flex justify-content-between p-5">
<% if user_signed_in? && current_user.id == @user.id%>
	<div>
		<%= render template: 'posts/new'%>
	</div>
	<div>
		<%= image_tag @user.avatar %>
		<br>
		<br>
		<%#=button_to 'Follow me', user_following_path(@user) %>
	</div>
	<%end%>
</div>
<br>
<div class="d-flex flex-column align-items-center">

	<div class="container">
	<% if @posts.present? %>
	<% @posts.each do |post| %>
	<%= post.user.name %>
	<% if post.images.attached? %>
	<br>
	<% if post.images.size > 1 %>
		<div class="row">
			<div class="col-3">
					<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<% post.images.each do |image| %>
							<% end %>
						</ol>

						<div class="carousel-inner">
							<div class="carousel-item active">
								<%= link_to image_tag(post.images.first, size: 250), post_path(post), class: "d-block w-100" %>
							</div>
							<% post.images.drop(1).each do |image| %>
							<div class="carousel-item">
								<%= link_to image_tag(image, size: 250), post_path(post), class: "d-block w-100" %>
							</div>
							<% end %>
						</div>
						<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
							<span class="carousel-control-prev-icon" aria-hidden="true"></span>
							<span class="sr-only">Previous</span>
						</a>
						<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
							<span class="carousel-control-next-icon" aria-hidden="true"></span>
							<span class="sr-only">Next</span>
						</a>

				<% else %>
				<% post.images.each do |image| %>
						<%= link_to image_tag(image, size: 250), post_path(post) %>
				<% end %>
				<% end %>
				<% end %>

				<br>
				-----------------------------------------------
				<br>
				<br>
				<% if user_signed_in? && current_user.id == @user.id %>
				<% if post.likes.exists?(post.likes.where(user_id: current_user.id)) %>
				
				<%=link_to 'dislike', user_dislike_path(current_user.id, post.id), method: :delete %>
				<%else%>
				<%=link_to 'like', user_like_path(current_user.id, post.id) %>
				<br>
				<%= pluralize(post.likes.count, "like") %>
				<%end%>
				<%end%>

				<br>
				<br>
				<%= post.user.name%>:
				<%= post.description %>
				<br>
				<% post.comments.each do |comment| %>
				<%= comment.user.name%> said:
				<%= comment.content%>
				<br>
				<%end%>
				<br>
				<%= render 'comments/new', post: post if user_signed_in? %>

				<% end %>	
				<% end %>
				<br>
			</div>
		</div>
	</div>
</div>
				</div>

app/views/posts/new.html.erb
<%= form_for [@user, @user.posts.build], local: true do |form| %>
  <div class="field">
    <%= form.label 'Description of post' %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.description %>
  <% @post.images.each do |image| %>
  <%= image_tag image %>
  <% end %>
</p>

<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
  
</p>